FROM public.ecr.aws/lambda/python:3.9
WORKDIR /var/task

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY iv_lambda.py .
COPY scraper/ ./scraper/

CMD ["iv_lambda.lambda_handler"] 